arch: 
  - arm64
language: node_js
node_js: 
  - 14.16
before_script: 
  - "npm install"
script: "true"
after_script: []
before_install: []
install: []
after_install: []
build: 
  - npm start
after_script: 
  - "echo done"
after_success: []
after_failure: []
before_deploy: []
deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: <encrypted access_key_id>
    secret_access_key: <encrypted secret_access_key>
    bucket: <bucket>
    key: <bucket_key>
    application: <app>
    deployment_group: <deployment_group>
    edge: true # opt in to dpl v2after_deploy: []
after_script: []
