arch: 
  - arm64
language: node_js
node_js: 
  - 14.16
before_script: 
  - "npm install"
script: "true"
after_script: []
before_install: []
install: []
after_install: []
build: 
  - npm start
after_script: 
  - "echo done"
after_success: []
after_failure: []
before_deploy: []
deploy:
  - provider: s3
  - provider: codedeploy
    access_key_id: $AWSAccessKeyId
    secret_access_key: $AWSSecretKey
    bucket: "S3 Bucket"
    key: latest/MyApp.zip
    application: SuperMan
    deployment_group: SuperManGroup
